use crate::ecs::components::BuildingEffect;
use crate::protocol::BuildingTypeKind;

/// Static definition for a building type, describing its cost, size, construction
/// requirements, and gameplay effects.
pub struct BuildingDefinition {
    pub kind: BuildingTypeKind,
    pub name: &'static str,
    pub tier: u8,
    pub token_cost: i64,
    pub build_time: f32,
    pub width: u32,
    pub height: u32,
    pub light_source: Option<(f32, (f32, f32, f32))>,
    pub effects: Vec<BuildingEffect>,
    pub description: &'static str,
}

/// Returns the canonical [`BuildingDefinition`] for the given building kind.
pub fn get_building_definition(kind: &BuildingTypeKind) -> BuildingDefinition {
    match kind {
        // ── Infrastructure ────────────────────────────────────────────
        BuildingTypeKind::Pylon => BuildingDefinition {
            kind: *kind,
            name: "Pylon",
            tier: 0,
            token_cost: 30,
            build_time: 100.0,
            width: 2,
            height: 2,
            light_source: Some((200.0, (1.0, 0.85, 0.5))),
            effects: vec![],
            description: "Illuminates surrounding area. Safety.",
        },
        BuildingTypeKind::ComputeFarm => BuildingDefinition {
            kind: *kind,
            name: "Compute Farm",
            tier: 0,
            token_cost: 80,
            build_time: 300.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.5)],
            description: "Rows of humming racks. Tokens trickle in.",
        },

        // ── Tier 1 ───────────────────────────────────────────────────
        BuildingTypeKind::TodoApp => BuildingDefinition {
            kind: *kind,
            name: "Todo App",
            tier: 1,
            token_cost: 50,
            build_time: 80.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.02)],
            description: "task: survive. status: in progress.",
        },
        BuildingTypeKind::Calculator => BuildingDefinition {
            kind: *kind,
            name: "Calculator",
            tier: 1,
            token_cost: 60,
            build_time: 90.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![],
            description: "It adds up. Mostly.",
        },
        BuildingTypeKind::LandingPage => BuildingDefinition {
            kind: *kind,
            name: "Landing Page",
            tier: 1,
            token_cost: 40,
            build_time: 70.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.05)],
            description: "Inspires the team with a clean hero section.",
        },

        // ── Tier 2 ───────────────────────────────────────────────────
        BuildingTypeKind::WeatherDashboard => BuildingDefinition {
            kind: *kind,
            name: "Weather Dashboard",
            tier: 2,
            token_cost: 120,
            build_time: 250.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.1)],
            description: "The forecast is always the same: dark.",
        },
        BuildingTypeKind::ChatApp => BuildingDefinition {
            kind: *kind,
            name: "Chat App",
            tier: 2,
            token_cost: 150,
            build_time: 300.0,
            width: 3,
            height: 3,
            light_source: Some((60.0, (0.3, 0.9, 0.4))),
            effects: vec![BuildingEffect::AgentMoraleBoost(0.1)],
            description: "Real-time messages in real-time darkness.",
        },
        BuildingTypeKind::KanbanBoard => BuildingDefinition {
            kind: *kind,
            name: "Kanban Board",
            tier: 2,
            token_cost: 130,
            build_time: 280.0,
            width: 3,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::BuildSpeedBoost(0.15)],
            description: "Drag tasks from To-Do to Done. Mostly the other direction.",
        },

        // ── Tier 3 ───────────────────────────────────────────────────
        BuildingTypeKind::EcommerceStore => BuildingDefinition {
            kind: *kind,
            name: "E-commerce Store",
            tier: 3,
            token_cost: 250,
            build_time: 500.0,
            width: 4,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.3)],
            description: "Buy. Sell. Survive. In that order.",
        },
        BuildingTypeKind::AiImageGenerator => BuildingDefinition {
            kind: *kind,
            name: "AI Image Generator",
            tier: 3,
            token_cost: 300,
            build_time: 550.0,
            width: 3,
            height: 3,
            light_source: Some((80.0, (0.6, 0.4, 1.0))),
            effects: vec![BuildingEffect::PassiveIncome(0.25)],
            description: "Generates visions of a world that doesn't exist yet.",
        },
        BuildingTypeKind::ApiDashboard => BuildingDefinition {
            kind: *kind,
            name: "API Dashboard",
            tier: 3,
            token_cost: 280,
            build_time: 480.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::ErrorRateReduction(0.15)],
            description: "Endpoints charted. Uptime: questionable.",
        },

        // ── Tier 4 ───────────────────────────────────────────────────
        BuildingTypeKind::Blockchain => BuildingDefinition {
            kind: *kind,
            name: "Blockchain",
            tier: 4,
            token_cost: 500,
            build_time: 800.0,
            width: 4,
            height: 4,
            light_source: Some((70.0, (0.2, 0.8, 0.9))),
            effects: vec![BuildingEffect::PassiveIncome(1.0)],
            description: "Immutable. Decentralized. Unnecessary.",
        },
    }
}
