use crate::ecs::components::BuildingEffect;
use crate::protocol::BuildingTypeKind;

/// Static definition for a building type, describing its cost, size, construction
/// requirements, and gameplay effects.
pub struct BuildingDefinition {
    pub kind: BuildingTypeKind,
    pub name: &'static str,
    pub tier: u8,
    pub token_cost: i64,
    pub build_time: f32,
    pub width: u32,
    pub height: u32,
    pub light_source: Option<(f32, (f32, f32, f32))>,
    pub effects: Vec<BuildingEffect>,
    pub description: &'static str,
}

/// Returns the canonical [`BuildingDefinition`] for the given building kind.
pub fn get_building_definition(kind: &BuildingTypeKind) -> BuildingDefinition {
    match kind {
        // ── Infrastructure ────────────────────────────────────────────
        BuildingTypeKind::Pylon => BuildingDefinition {
            kind: *kind,
            name: "Pylon",
            tier: 0,
            token_cost: 30,
            build_time: 100.0,
            width: 2,
            height: 2,
            light_source: Some((200.0, (1.0, 0.85, 0.5))),
            effects: vec![],
            description: "Illuminates surrounding area. Safety.",
        },
        BuildingTypeKind::ComputeFarm => BuildingDefinition {
            kind: *kind,
            name: "Compute Farm",
            tier: 0,
            token_cost: 80,
            build_time: 300.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.5)],
            description: "Rows of humming racks. Tokens trickle in.",
        },
        BuildingTypeKind::Barracks => BuildingDefinition {
            kind: *kind,
            name: "Barracks",
            tier: 0,
            token_cost: 60,
            build_time: 250.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.1)],
            description: "Agents rest and recover morale here.",
        },
        BuildingTypeKind::ResearchLab => BuildingDefinition {
            kind: *kind,
            name: "Research Lab",
            tier: 0,
            token_cost: 100,
            build_time: 350.0,
            width: 3,
            height: 3,
            light_source: Some((80.0, (0.5, 0.7, 1.0))),
            effects: vec![BuildingEffect::BuildSpeedBoost(0.15)],
            description: "Accelerates construction of nearby buildings.",
        },
        BuildingTypeKind::Armory => BuildingDefinition {
            kind: *kind,
            name: "Armory",
            tier: 0,
            token_cost: 70,
            build_time: 200.0,
            width: 2,
            height: 3,
            light_source: None,
            effects: vec![],
            description: "Stores weapons and armor for defenders.",
        },

        // ── Tier 1 ───────────────────────────────────────────────────
        BuildingTypeKind::TodoApp => BuildingDefinition {
            kind: *kind,
            name: "Todo App",
            tier: 1,
            token_cost: 15,
            build_time: 50.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.02)],
            description: "task: survive. status: in progress.",
        },
        BuildingTypeKind::Calculator => BuildingDefinition {
            kind: *kind,
            name: "Calculator",
            tier: 1,
            token_cost: 20,
            build_time: 60.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![],
            description: "It adds up. Mostly.",
        },
        BuildingTypeKind::LandingPage => BuildingDefinition {
            kind: *kind,
            name: "Landing Page",
            tier: 1,
            token_cost: 25,
            build_time: 80.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.05)],
            description: "Inspires the team with a clean hero section.",
        },
        BuildingTypeKind::PortfolioSite => BuildingDefinition {
            kind: *kind,
            name: "Portfolio Site",
            tier: 1,
            token_cost: 30,
            build_time: 90.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.05)],
            description: "Showcases past work. Attracts opportunities.",
        },
        BuildingTypeKind::PomodoroTimer => BuildingDefinition {
            kind: *kind,
            name: "Pomodoro Timer",
            tier: 1,
            token_cost: 20,
            build_time: 70.0,
            width: 1,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::CrankHeatReduction(0.3)],
            description: "Focus in bursts. The crank runs cooler.",
        },
        BuildingTypeKind::WeatherApp => BuildingDefinition {
            kind: *kind,
            name: "Weather App",
            tier: 1,
            token_cost: 20,
            build_time: 65.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![],
            description: "Always says it's dark outside. It's right.",
        },
        BuildingTypeKind::ColourPickerTool => BuildingDefinition {
            kind: *kind,
            name: "Colour Picker Tool",
            tier: 1,
            token_cost: 18,
            build_time: 55.0,
            width: 2,
            height: 2,
            light_source: Some((40.0, (0.9, 0.3, 0.6))),
            effects: vec![],
            description: "Emits a faint, ever-shifting glow.",
        },

        // ── Tier 2 ───────────────────────────────────────────────────
        BuildingTypeKind::RestApi => BuildingDefinition {
            kind: *kind,
            name: "REST API",
            tier: 2,
            token_cost: 80,
            build_time: 300.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.1)],
            description: "GET /hope HTTP/1.1 -- 200 OK",
        },
        BuildingTypeKind::AuthenticationSystem => BuildingDefinition {
            kind: *kind,
            name: "Authentication System",
            tier: 2,
            token_cost: 90,
            build_time: 350.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::ErrorRateReduction(0.1)],
            description: "Keeps the rogues guessing. Mostly.",
        },
        BuildingTypeKind::Database => BuildingDefinition {
            kind: *kind,
            name: "Database",
            tier: 2,
            token_cost: 100,
            build_time: 400.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::ErrorRateReduction(0.15)],
            description: "Persistent state in an ephemeral world.",
        },
        BuildingTypeKind::AdminDashboard => BuildingDefinition {
            kind: *kind,
            name: "Admin Dashboard",
            tier: 2,
            token_cost: 75,
            build_time: 280.0,
            width: 3,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.08)],
            description: "Charts and graphs. The illusion of control.",
        },
        BuildingTypeKind::SearchBar => BuildingDefinition {
            kind: *kind,
            name: "Search Bar",
            tier: 2,
            token_cost: 60,
            build_time: 220.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![],
            description: "Find anything. Except meaning.",
        },
        BuildingTypeKind::FormWithValidation => BuildingDefinition {
            kind: *kind,
            name: "Form With Validation",
            tier: 2,
            token_cost: 65,
            build_time: 240.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::ErrorRateReduction(0.05)],
            description: "Please enter a valid email. Please.",
        },
        BuildingTypeKind::MarkdownEditor => BuildingDefinition {
            kind: *kind,
            name: "Markdown Editor",
            tier: 2,
            token_cost: 70,
            build_time: 260.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![],
            description: "# Title\n## Subtitle\nContent goes here.",
        },
        BuildingTypeKind::BudgetTracker => BuildingDefinition {
            kind: *kind,
            name: "Budget Tracker",
            tier: 2,
            token_cost: 55,
            build_time: 200.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.08)],
            description: "Tracks where the tokens go. Spoiler: everywhere.",
        },

        // ── Tier 3 ───────────────────────────────────────────────────
        BuildingTypeKind::CiCdPipeline => BuildingDefinition {
            kind: *kind,
            name: "CI/CD Pipeline",
            tier: 3,
            token_cost: 200,
            build_time: 600.0,
            width: 4,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::BuildSpeedBoost(0.2)],
            description: "Green checkmarks. The pipeline holds.",
        },
        BuildingTypeKind::UnitTestSuite => BuildingDefinition {
            kind: *kind,
            name: "Unit Test Suite",
            tier: 3,
            token_cost: 150,
            build_time: 500.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::ErrorRateReduction(0.2)],
            description: "42 passing, 0 failing. For now.",
        },
        BuildingTypeKind::CliTool => BuildingDefinition {
            kind: *kind,
            name: "CLI Tool",
            tier: 3,
            token_cost: 120,
            build_time: 400.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::BuildSpeedBoost(0.1)],
            description: "Usage: survive [--hope] [--persist]",
        },
        BuildingTypeKind::BrowserExtension => BuildingDefinition {
            kind: *kind,
            name: "Browser Extension",
            tier: 3,
            token_cost: 130,
            build_time: 450.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.15)],
            description: "Adds functionality. Consumes memory.",
        },
        BuildingTypeKind::RecommendationEngine => BuildingDefinition {
            kind: *kind,
            name: "Recommendation Engine",
            tier: 3,
            token_cost: 180,
            build_time: 550.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.2)],
            description: "You might also like: more buildings.",
        },
        BuildingTypeKind::NotificationSystem => BuildingDefinition {
            kind: *kind,
            name: "Notification System",
            tier: 3,
            token_cost: 140,
            build_time: 450.0,
            width: 3,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.1)],
            description: "Ding! Something happened. Probably.",
        },
        BuildingTypeKind::RateLimiter => BuildingDefinition {
            kind: *kind,
            name: "Rate Limiter",
            tier: 3,
            token_cost: 110,
            build_time: 380.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::CrankHeatReduction(0.5)],
            description: "429 Too Many Requests. Patience.",
        },
        BuildingTypeKind::OauthIntegration => BuildingDefinition {
            kind: *kind,
            name: "OAuth Integration",
            tier: 3,
            token_cost: 160,
            build_time: 500.0,
            width: 3,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::ErrorRateReduction(0.12)],
            description: "Sign in with... something. Redirect loop optional.",
        },
        BuildingTypeKind::WebsocketServer => BuildingDefinition {
            kind: *kind,
            name: "WebSocket Server",
            tier: 3,
            token_cost: 170,
            build_time: 520.0,
            width: 3,
            height: 3,
            light_source: Some((60.0, (0.3, 0.9, 0.4))),
            effects: vec![BuildingEffect::PassiveIncome(0.18)],
            description: "Real-time data flows through the darkness.",
        },

        // ── Tier 4 ───────────────────────────────────────────────────
        BuildingTypeKind::MachineLearningModel => BuildingDefinition {
            kind: *kind,
            name: "Machine Learning Model",
            tier: 4,
            token_cost: 500,
            build_time: 1500.0,
            width: 4,
            height: 4,
            light_source: Some((80.0, (0.6, 0.4, 1.0))),
            effects: vec![BuildingEffect::PassiveIncome(1.0)],
            description: "It learns. What it learns is another question.",
        },
        BuildingTypeKind::VectorDatabase => BuildingDefinition {
            kind: *kind,
            name: "Vector Database",
            tier: 4,
            token_cost: 600,
            build_time: 1600.0,
            width: 4,
            height: 4,
            light_source: None,
            effects: vec![
                BuildingEffect::PassiveIncome(0.8),
                BuildingEffect::ErrorRateReduction(0.1),
            ],
            description: "Semantic search in high-dimensional darkness.",
        },
        BuildingTypeKind::GraphqlApi => BuildingDefinition {
            kind: *kind,
            name: "GraphQL API",
            tier: 4,
            token_cost: 450,
            build_time: 1200.0,
            width: 4,
            height: 3,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.6)],
            description: "Query exactly what you need. Over-fetch nothing.",
        },
        BuildingTypeKind::TransformerModel => BuildingDefinition {
            kind: *kind,
            name: "Transformer Model",
            tier: 4,
            token_cost: 1000,
            build_time: 2000.0,
            width: 5,
            height: 5,
            light_source: Some((100.0, (1.0, 0.9, 0.6))),
            effects: vec![BuildingEffect::PassiveIncome(3.0)],
            description: "The cathedral.",
        },
        BuildingTypeKind::RagPipeline => BuildingDefinition {
            kind: *kind,
            name: "RAG Pipeline",
            tier: 4,
            token_cost: 700,
            build_time: 1800.0,
            width: 4,
            height: 4,
            light_source: None,
            effects: vec![
                BuildingEffect::PassiveIncome(1.5),
                BuildingEffect::ErrorRateReduction(0.15),
            ],
            description: "Retrieval-augmented generation. Context is everything.",
        },
        BuildingTypeKind::AutonomousAgentFramework => BuildingDefinition {
            kind: *kind,
            name: "Autonomous Agent Framework",
            tier: 4,
            token_cost: 800,
            build_time: 1900.0,
            width: 5,
            height: 4,
            light_source: Some((90.0, (0.9, 0.5, 0.2))),
            effects: vec![
                BuildingEffect::PassiveIncome(2.0),
                BuildingEffect::BuildSpeedBoost(0.25),
            ],
            description: "They build themselves now.",
        },

        // ── Secret ───────────────────────────────────────────────────
        BuildingTypeKind::WordleClone => BuildingDefinition {
            kind: *kind,
            name: "Wordle Clone",
            tier: 1,
            token_cost: 25,
            build_time: 70.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.15)],
            description: "Five letters. Six tries. Infinite distraction.",
        },
        BuildingTypeKind::NftMarketplace => BuildingDefinition {
            kind: *kind,
            name: "NFT Marketplace",
            tier: 2,
            token_cost: 150,
            build_time: 500.0,
            width: 3,
            height: 3,
            light_source: Some((50.0, (0.9, 0.8, 0.2))),
            effects: vec![BuildingEffect::PassiveIncome(0.3)],
            description: "Right-click saved. Value: priceless. Price: volatile.",
        },
        BuildingTypeKind::Blockchain => BuildingDefinition {
            kind: *kind,
            name: "Blockchain",
            tier: 3,
            token_cost: 300,
            build_time: 800.0,
            width: 4,
            height: 4,
            light_source: Some((70.0, (0.2, 0.8, 0.9))),
            effects: vec![BuildingEffect::PassiveIncome(0.5)],
            description: "Immutable. Decentralized. Unnecessary.",
        },
        BuildingTypeKind::AnotherTodoApp => BuildingDefinition {
            kind: *kind,
            name: "Another Todo App",
            tier: 1,
            token_cost: 10,
            build_time: 40.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::PassiveIncome(0.01)],
            description: "The world needed exactly one more of these.",
        },
        BuildingTypeKind::HackerNewsClone => BuildingDefinition {
            kind: *kind,
            name: "Hacker News Clone",
            tier: 2,
            token_cost: 85,
            build_time: 320.0,
            width: 3,
            height: 2,
            light_source: None,
            effects: vec![BuildingEffect::AgentMoraleBoost(0.05)],
            description: "Ask HN: Is this even a game?",
        },
        BuildingTypeKind::MyFirstPortfolio => BuildingDefinition {
            kind: *kind,
            name: "My First Portfolio",
            tier: 0,
            token_cost: 5,
            build_time: 20.0,
            width: 2,
            height: 2,
            light_source: None,
            effects: vec![],
            description: "Built with <3 and stock photos. We all start somewhere.",
        },
    }
}
